### PR TITLE
Release new version

### PR DESCRIPTION
**Pull request by micles123**
Please release a new version of appender with fixed native library

### CODE REVIEW

**Comment by bwaldvogel** [comment]
+1

**Comment by satabin** [comment]
If I have no news from @micles123 within the next day, I will add my remarks to his commit and release it this weekend.

**Comment by satabin** [comment]
Merged in b0250f57d5be3fc9bfe0021ceaa83566de9225df

**Comment by satabin** [comment]
Release 0.2.0 published to sonatype repositories. It will be propagated to the maven central repository within a few hours. Thanks @micles123 for this contribution.

**Pull request closed without merging**
